
name: Nightly Scraper
on:
  schedule:
    # GitHub’s cron uses UTC → 07:00 UTC = 02:00 America/Chicago
    - cron:  '0 7 * * *'
  workflow_dispatch:     # optional “Run” button
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install -r requirements.txt
      - run: python -m playwright install --with-deps chromium
      - name: Run scraper
        run: python bellingrath_events.py
      # - name: Send to webhook
      #   env:
      #     WEBHOOK: ${{ secrets.WEBHOOK_URL }}
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" \
      #          -d @output.json "$WEBHOOK"
